(define
    (problem NailBoxProblem2)
    (:domain NailBoxDomain)
    (:objects a b c d e f g h i j)
    (:init
        (on-table a)
        (on b a)
        (on c b)
        (clear c)
        (on-table d)
        (clear d)
        (on-table e)
        (clear e)
        (on-table f)
        (on h f)
        (clear h)
        (on-table g)
        (on i g)
        (clear i)
        (on-table j)
        (clear j)
        (free-arm)
    )
    (:goal
        (and
            (hammered a e g)
            (on-table h)
            (on-table j)
        )
    )
)
